### ISSUE TITLE
Logger object?

### ISSUE THREAD

**Issue by mike239x** [emilk/loguru#116]
Hi, I was looking through multiple logging libraries and I saw that many have some kind of notion of different loggers (with their own severity levels and output style and sinks), and I was wondering if loguru has anything like that? I looked in the documentation but it seems there is only one main logger...

**Comment by emilk** [comment]
Loguru only has a global logger. You can set up multiple _outputs_ with different severity and output styles, but that is not quite what you are asking for.

**Comment by mike239x** [comment]
I see. Thanks for the quick answer!

**Comment by DavidAntliff** [comment]
@emilk Perhaps related to this, I have a project that uses loguru compiled into a dynamic library, but there's something about loguru that prevents the library from being unloaded when `dlclose` is called. If loguru is not linked with the library, the dynamic library is unloaded correctly. I'm not sure what exactly is getting in the way. Do you think that this is due to the "global logger" you mention? Or is it more likely to be signal handlers or even threads that it installs?

**Comment by emilk** [comment]
@DavidAntliff maybe you need to call [`loguru::shutdown()`](https://emilk.github.io/loguru/index.html#functions/voidshutdown()) ?

**Comment by DavidAntliff** [comment]
Thanks, I missed that one, I'll give it a try.

**Comment by DavidAntliff** [comment]
Just to follow up for completeness, the "culprit" was this line:

`static LOGURU_THREAD_LOCAL ECPtr thread_ec_ptr = nullptr;`

Using thread-local storage prevents the dynamic library from being unloaded.

There's a workaround that's specific to the project I'm working on, so no worries, this is really just an "informational" comment.

Looks like my associate has already logged this here, too: https://github.com/emilk/loguru/issues/146
