### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by sailfish009** [emilk/loguru#27]
Hi, how to use loguru callback function?
i am trying to send error message to another thread. 

to use it, i tried to use event queue from mbed-events library.
it seems work fine.
https://github.com/ARMmbed/mbed-events

**Comment by sailfish009** [comment]
without "EventQueue" and only with loguru,
how do i use the function?

i just wonder that whether loguru support the functionality or not.

**Comment by zao** [comment]
I'm not sure I follow what you're actually asking about.

Loguru invokes the callback in the thread that performs the log_message call. It's up to you to write logic in this synchronous callback to communicate information to some other thread of yours.

Could you please explain what functionality it is you're looking for that could be built into Loguru? What problem are you trying to solve with this?

**Comment by sailfish009** [comment]
it would be good if loguru support eventqueue,
i need some callback functionality which take care of getting error messages,
and back to user application.

now i have implemented simple function using mbed-events library,
what i try to say is one tool is enough, two is too much.

**Comment by sailfish009** [comment]
as of the result, my use case is like below:

```
if(error)
{
#if DEBUG
  LOG_ERROR("error message\n");
#else 
  function(...);
#endif
}
```

**Comment by emilk** [comment]
I understand your desire for an easy way to collect log messages in a queue, but I feel this is outside the scope of Loguru. As @zao pointed out you can rather easily use the log callback functionality in loguru to collect messages and process them as you want.

I prefer making Loguru a library that allows for easy "gluing" like this, rather than one which comes pre-glued with big dependencies.

Or in other words: Loguru's aim is to be a lightweight logging library, not a framework for processing logging messages.
