### ISSUE TITLE
Option to not abort on FATAL

### ISSUE THREAD

**Issue by NN---** [emilk/loguru#73]
It would be nice to have abort as optional behavior for FATAL log level without throwing exception.

**Comment by emilk** [comment]
You mean as an extra log level? I could be done I suppose, but can you give me a motivating example?

**Comment by legends2k** [comment]
@emilk Having an option to build loguru with exceptions turned off will be useful; it can be used in projects which don't use C++ exceptions like games and embedded software.

**Comment by emilk** [comment]
well, `loguru` does not throw any exceptions, so it should be fine to use anywhere.
It does calls `abort` on `CHECK`-fail or when someone calls `ABORT_F`, so I think this issue is based on a misunderstanding

**Comment by legends2k** [comment]
@emilk I agree that `loguru` itself doesn't have any `throw` statements, but that doesn't suffice to compile it with exceptions turned off (`-fno-exceptions`); there're a couple of `try-catch` statements in the code.  One is due to the usage of `std::regex_replace` and the other is wrapping `log_message`.
