### ISSUE TITLE
Compilation of implentation is slow

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [emilk/loguru#77]
This library seems interesting and well designed, but compilation is slow here.
Any idea of where the bottleneck is, and perhaps how it could be trimmed down to compile faster?
Fortunately, compilation time is reduced to ~0.4s when not `#define LOGURU_IMPLEMENTATION 1`, so the problem should be solved by defining a dedicated compilation unit (cpp file) for that.

Ubuntu 18.04 running on a Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz . 
This is obviously not IO-bound (fast SSD, 16GB RAM, files in cache).
System is otherwise idle.

```
# Compilation options from the `loguru_example/CMakeLists.txt` :
time /usr/bin/c++    -std=c++11 -Werror -Wall -Wextra -pedantic -fsanitize=address -fno-omit-frame-pointer -O2 -g -DNDEBUG   -o main.cpp.o -c main.cpp

# Various runs :

real	0m10,722s
user	0m10,533s
sys	0m0,170s

real	0m11,182s
user	0m11,048s
sys	0m0,132s

real	0m11,360s
user	0m11,176s
sys	0m0,180s

real	0m11,439s
user	0m11,222s
sys	0m0,217s

```

**Comment by emilk** [comment]
Loguru is designed to have `#define LOGURU_IMPLEMENTATION 1` in one cpp that you compile once and then never again (assuming you have a compile cache or a decent build system). The main thing is that to include the Loguru header should not slow down compilation much at all, because it is very slim (it does not `#include` anything). In other words: it is a one-time upfront compilation cost, and then a minimal overhead to your everyday recompilation.

That being said, 10 seconds sounds too much.

BUT: `-fsanitize=address -fno-omit-frame-pointer` is for finding memory errors. You don't need them. So really what you should be testing is this:

`time /usr/bin/c++ -std=c++11 -O2 -DNDEBUG -o main.cpp.o -c main.cpp`

it should be a bit faster. On my laptop it clocks in at about 3.5s

**Comment by emilk** [comment]
Loguru is now split into a `.hpp` and a `.cpp` file. Maybe that will help you. In any case, I'm closing this issue.

**Comment by fidergo-stephane-gourichon** [comment]
Just as quick feedback. With commit 0ef2eeae427a9f20510174d9451924f9d26b39e7 :

```
time /usr/bin/c++    -std=c++11 -Werror -Wall -Wextra -pedantic -fsanitize=address -fno-omit-frame-pointer -O2 -g -DNDEBUG   -o main.cpp.o -c main.cpp

real	0m7,287s
user	0m6,915s
sys	0m0,083s

$ time /usr/bin/c++ -std=c++11 -O2 -DNDEBUG -o main.cpp.o -c main.cpp

real	0m3,849s
user	0m3,769s
sys	0m0,060s

$ time /usr/bin/c++ -std=c++11 -O2 -DNDEBUG -o main.cpp.o -c main.cpp

real	0m3,798s
user	0m3,734s
sys	0m0,049s

$ time /usr/bin/c++ -std=c++11 -O2 -DNDEBUG -o main.cpp.o -c main.cpp

real	0m3,790s
user	0m3,729s
sys	0m0,044s
```

> Loguru is now split into a .hpp and a .cpp file. Maybe that will help you. In any case, I'm closing this issue.

Not tested, but I guess it will indeed speed up things, to pay the 3 seconds cost only once and not at each compilation.

Cheers and keep up the good works!
