### ISSUE TITLE
Break up into hpp/cpp

### ISSUE THREAD

**Issue by emilk** [emilk/loguru#83]
I am considering breaking up Loguru into a `loguru.hpp` and a `loguru.cpp`.

In practice this means:

* You can compile `loguru.cpp` and link with it easier
* Or you can `#include <loguru.cpp>` if you prefer (only no need for `#define LOGURU_IMPLEMENTATION 1`)
* One more file you need to keep track of in your build systems
	
So: good idea or bad idea?

**Comment by ypujante** [comment]
I am definitely up for simpler code that doesn't depend on includes and that clearly separates what can be compiled once vs included all the time...

In my case (https://github.com/pongasoft/jamba/tree/master/src/cpp/pongasoft/logging) it is very well isolated since all my code includes "logging.h" which does the right thing... so it would be very easy to change...
